#[cfg(test)]
use bytes::{BytesMut, BufMut};

use crate::config::AwgParams;
use crate::responder::{Protocol, classify_awg_packet};

/// Apply protocol-conformant padding transformation to an outgoing packet.
///
/// AmneziaWG prepends random padding bytes (S1–S4) before the obfuscated
/// header. When imitating a specific protocol, we overwrite this leading
/// padding region (`data[0..pad_size]`) with protocol-conformant filler so
/// that DPI sees plausible traffic.
///
/// The `pad_size` parameter indicates how many leading bytes are padding.
/// Everything from `data[pad_size..]` is the real WireGuard payload (header +
/// body) and is used for PRNG seeding but never modified.
///
/// If `pad_size == 0` or `pad_size >= data.len()`, no transformation is
/// applied.
///
/// Protocol-specific padding strategies:
/// - **QUIC**: Pseudo-random bytes resembling encrypted QUIC payload (high
///   entropy), with a QUIC short-header form byte at the start.
/// - **DNS**: DNS response header structure (transaction ID, flags, section
///   counts) followed by zero-fill for EDNS OPT padding (RFC 7830).
/// - **SIP**: SIP header continuation text (`Via:`, `Content-Length:`)
///   ending with CRLF.
pub fn apply_padding(data: &mut [u8], pad_size: usize, proto: Protocol) {
    if pad_size == 0 || pad_size >= data.len() {
        return;
    }

    match proto {
        Protocol::Quic => apply_quic_padding(data, pad_size),
        Protocol::Dns => apply_dns_padding(data, pad_size),
        Protocol::Sip => apply_sip_padding(data, pad_size),
    }
}

/// Apply AWG-aware padding transformation to an outgoing packet.
///
/// Classifies the packet using the S-offset / H-range pairs to determine its
/// type, then overwrites the leading S-padding prefix with protocol-conformant
/// filler.
///
/// Returns `true` if the packet was classified and transformed, `false` if the
/// packet type could not be identified (e.g. junk packet) and was left
/// unchanged.
pub fn apply_awg_transform(
    data: &mut [u8],
    params: &AwgParams,
    proto: Protocol,
) -> bool {
    let pkt_type = match classify_awg_packet(data, params) {
        Some(t) => t,
        None => return false,
    };

    let pad_size = pkt_type.padding_size(params);
    let total = data.len();

    if pad_size == 0 || pad_size >= total {
        return false;
    }

    apply_padding(data, pad_size, proto);
    true
}

/// Build a complete packet with protocol-conformant padding prepended.
///
/// Takes the original payload and prepends `pad_len` bytes of
/// protocol-conformant padding.  `pad_len` is silently clamped to
/// `MAX_PAD_LEN` (1024) to prevent excessive allocation — AmneziaWG
/// S-values are typically well below this limit.
#[cfg(test)]
const MAX_PAD_LEN: usize = 1_024;

#[cfg(test)]
pub(crate) fn build_padded_packet(payload: &[u8], pad_len: usize, proto: Protocol) -> BytesMut {
    let pad_len = pad_len.min(MAX_PAD_LEN);
    let mut buf = BytesMut::with_capacity(pad_len + payload.len());

    // Prepend padding bytes (initially zeros) before the payload
    buf.put_bytes(0, pad_len);
    buf.put_slice(payload);

    if pad_len == 0 {
        return buf;
    }

    apply_padding(&mut buf[..], pad_len, proto);

    buf
}

// ---------------------------------------------------------------------------
// Protocol-specific padding implementations
// ---------------------------------------------------------------------------

/// QUIC-style padding: pseudo-random bytes resembling encrypted QUIC payload.
///
/// Encrypted QUIC data has high entropy (uniform byte distribution). The first
/// byte uses the QUIC short-header form (fixed bit set, `0x40`), and remaining
/// bytes are generated by a deterministic PRNG seeded from the packet payload
/// (which follows the padding).
/// This makes the padding indistinguishable from encrypted QUIC payload to
/// statistical DPI analysis.
fn apply_quic_padding(data: &mut [u8], pad_size: usize) {
    let (padding, payload) = data.split_at_mut(pad_size);
    if padding.is_empty() {
        return;
    }

    // Seed PRNG from payload bytes (after the padding) using FNV-1a hash
    let mut state: u32 = 0x811c_9dc5;
    for &b in payload.iter().take(64) {
        state ^= b as u32;
        state = state.wrapping_mul(0x0100_0193);
    }

    // Byte 0: QUIC short-header form byte (header form=0, fixed bit=1).
    // Randomize only allowed bits: spin (0x20), key phase (0x04), PN length (0x03),
    // while keeping reserved bits (0x18) cleared as per RFC 9000.
    let header_random = state as u8;
    let spin_bit = header_random & 0x20;
    let key_phase_bit = header_random & 0x04;
    let pn_len_bits = header_random & 0x03;
    padding[0] = 0x40 | spin_bit | key_phase_bit | pn_len_bits;
    state = lcg_step(state);

    // Remaining bytes: pseudo-random, simulating encrypted QUIC 1-RTT payload
    for byte in padding[1..].iter_mut() {
        *byte = (state >> 16) as u8;
        state = lcg_step(state);
    }
}

/// DNS-style padding: minimal DNS response header followed by zero padding.
///
/// Creates a plausible DNS response structure:
/// - Transaction ID derived from the packet payload (which follows the padding)
/// - Standard response flags (QR=1, RD=1, RA=1, RCODE=NOERROR)
/// - Remaining bytes are zero-filled for generic padding
fn apply_dns_padding(data: &mut [u8], pad_size: usize) {
    let (padding, payload) = data.split_at_mut(pad_size);
    if padding.is_empty() {
        return;
    }

    // Derive transaction ID from first two payload bytes (H header)
    let tx_hi = payload.first().copied().unwrap_or(0);
    let tx_lo = payload.get(1).copied().unwrap_or(0);

    // DNS response header (12 bytes)
    let header: [u8; 12] = [
        tx_hi, tx_lo,   // Transaction ID
        0x81, 0x80,     // Flags: QR=1, RD=1, RA=1, RCODE=NOERROR
        0x00, 0x00,     // QDCOUNT = 0 (no question section emitted)
        0x00, 0x00,     // ANCOUNT = 0
        0x00, 0x00,     // NSCOUNT = 0
        0x00, 0x00,     // ARCOUNT = 0 (no additional records emitted)
    ];

    let copy_len = std::cmp::min(padding.len(), header.len());
    padding[..copy_len].copy_from_slice(&header[..copy_len]);

    // Rest: zero-fill (generic padding content)
    for byte in padding[copy_len..].iter_mut() {
        *byte = 0x00;
    }
}

/// SIP-style padding: SIP header continuation text.
///
/// Fills the padding prefix with recognizable SIP header text (`Via:`,
/// `Content-Length:`) which makes the packet look like legitimate SIP
/// signaling traffic. The padding always ends with CRLF when space allows.
fn apply_sip_padding(data: &mut [u8], pad_size: usize) {
    let padding = &mut data[..pad_size];
    if padding.is_empty() {
        return;
    }

    let len = padding.len();

    // SIP header continuation text
    static SIP_FILL: &[u8] = b"Via: SIP/2.0/UDP proxy\r\nContent-Length: 0\r\n";

    // Fill padding by cycling through the SIP text
    let fill_len = SIP_FILL.len();
    let mut pos = 0;
    while pos < len {
        let remaining = len - pos;
        let chunk = std::cmp::min(remaining, fill_len);
        padding[pos..pos + chunk].copy_from_slice(&SIP_FILL[..chunk]);
        pos += chunk;
    }

    // Ensure the padding ends with \r\n if at least 2 bytes
    if len >= 2 {
        padding[len - 2] = b'\r';
        padding[len - 1] = b'\n';
    }
}

/// Linear congruential generator step (glibc constants).
fn lcg_step(state: u32) -> u32 {
    state.wrapping_mul(1_103_515_245).wrapping_add(12345)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::HRange;

    // -- QUIC padding tests --

    #[test]
    fn quic_padding_has_header_and_entropy() {
        // 10 bytes padding prefix + 10 bytes payload
        let mut data = vec![0xAA; 20];
        let pad_size = 10;
        apply_padding(&mut data, pad_size, Protocol::Quic);

        // First padding byte has QUIC fixed bit set (0x40)
        assert_eq!(
            data[0] & 0x40,
            0x40,
            "QUIC padding first byte should have fixed bit set"
        );
        // Reserved bits (0x18) must be cleared per RFC 9000
        assert_eq!(
            data[0] & 0x18,
            0x00,
            "QUIC padding first byte must have reserved bits cleared"
        );
        // Padding should contain non-zero bytes (high entropy, not all-zero)
        assert!(
            data[1..10].iter().any(|&b| b != 0x00),
            "QUIC padding should have non-zero bytes"
        );
        // Payload (last 10 bytes) untouched
        assert!(data[10..].iter().all(|&b| b == 0xAA));
    }

    #[test]
    fn quic_padding_varies_with_payload() {
        // Two different payloads should produce different padding
        let mut data_a = [0u8; 20];
        let mut data_b = [0u8; 20];
        // Set different payload content (bytes 10..20)
        data_a[10..].fill(0xAA);
        data_b[10..].fill(0xBB);
        apply_padding(&mut data_a, 10, Protocol::Quic);
        apply_padding(&mut data_b, 10, Protocol::Quic);
        // Padding regions (first 10 bytes) should differ (different seeds)
        assert_ne!(&data_a[..10], &data_b[..10]);
    }

    // -- DNS padding tests --

    #[test]
    fn dns_padding_has_response_header() {
        // 20 bytes padding prefix + 4 bytes payload
        let mut data = vec![0x00; 24];
        data[20..24].copy_from_slice(&[0xBB, 0xBB, 0xBB, 0xBB]);
        let pad_size = 20;
        apply_padding(&mut data, pad_size, Protocol::Dns);

        // DNS response header: TX ID derived from payload bytes
        assert_eq!(data[0], 0xBB); // tx_hi from payload[0]
        assert_eq!(data[1], 0xBB); // tx_lo from payload[1]
        // Flags: QR=1 (high bit of flags byte)
        assert_eq!(data[2] & 0x80, 0x80, "DNS QR bit should be set");
        assert_eq!(data[2], 0x81); // RD=1
        assert_eq!(data[3], 0x80); // RA=1
        // QDCOUNT = 0
        assert_eq!(data[4], 0x00);
        assert_eq!(data[5], 0x00);
        // After header (12 bytes), rest of padding should be zeros
        assert!(data[12..20].iter().all(|&b| b == 0x00));
        // Payload untouched
        assert!(data[20..24].iter().all(|&b| b == 0xBB));
    }

    #[test]
    fn dns_padding_short_fills_partial_header() {
        // Only 5 bytes of padding prefix — should fill what fits from DNS header
        let mut data = vec![0x00; 10];
        data[5..10].copy_from_slice(&[0xCC, 0xCC, 0xCC, 0xCC, 0xCC]);
        let pad_size = 5;
        apply_padding(&mut data, pad_size, Protocol::Dns);

        assert_eq!(data[0], 0xCC); // tx_hi from payload[0]
        assert_eq!(data[1], 0xCC); // tx_lo from payload[1]
        assert_eq!(data[2], 0x81); // flags high
        assert_eq!(data[3], 0x80); // flags low
        assert_eq!(data[4], 0x00); // QDCOUNT high
        // Payload untouched
        assert!(data[5..10].iter().all(|&b| b == 0xCC));
    }

    // -- SIP padding tests --

    #[test]
    fn sip_padding_has_sip_headers() {
        // 50 bytes padding prefix + 10 bytes payload
        let mut data = vec![0x00; 60];
        data[50..60].fill(0xCC);
        let pad_size = 50;
        apply_padding(&mut data, pad_size, Protocol::Sip);

        // Padding starts with "Via: SIP/2.0/..."
        let padding = &data[..50];
        assert!(padding.starts_with(b"Via: SIP"));
        // Padding ends with \r\n
        assert_eq!(data[48], b'\r');
        assert_eq!(data[49], b'\n');
        // Payload untouched
        assert!(data[50..60].iter().all(|&b| b == 0xCC));
    }

    #[test]
    fn sip_padding_single_byte() {
        let mut data = [0x00, 0xAA]; // 1 byte padding + 1 byte payload
        apply_padding(&mut data, 1, Protocol::Sip);
        assert_eq!(data[0], b'V');
        assert_eq!(data[1], 0xAA); // payload untouched
    }

    #[test]
    fn sip_padding_two_bytes() {
        let mut data = [0x00, 0x00, 0xAA]; // 2 bytes padding + 1 byte payload
        apply_padding(&mut data, 2, Protocol::Sip);
        // Two bytes: ends with \r\n
        assert_eq!(data[0], b'\r');
        assert_eq!(data[1], b'\n');
        assert_eq!(data[2], 0xAA); // payload untouched
    }

    // -- General padding tests --

    #[test]
    fn no_padding_when_pad_size_zero() {
        let mut data = vec![0xDD; 10];
        apply_padding(&mut data, 0, Protocol::Quic);
        assert!(data.iter().all(|&b| b == 0xDD));
    }

    #[test]
    fn no_padding_when_pad_size_equals_len() {
        let mut data = vec![0xDD; 10];
        apply_padding(&mut data, 10, Protocol::Quic);
        assert!(data.iter().all(|&b| b == 0xDD));
    }

    #[test]
    fn no_padding_when_pad_size_exceeds_len() {
        let mut data = vec![0xEE; 10];
        apply_padding(&mut data, 15, Protocol::Dns);
        assert!(data.iter().all(|&b| b == 0xEE));
    }

    // -- Build padded packet tests --

    #[test]
    fn build_padded_packet_quic() {
        let payload = vec![0x01, 0x02, 0x03];
        let result = build_padded_packet(&payload, 5, Protocol::Quic);
        assert_eq!(result.len(), 8);
        // Last 3 bytes are payload (prepended padding)
        assert_eq!(&result[5..8], &[0x01, 0x02, 0x03]);
        // First padding byte has QUIC fixed bit
        assert_eq!(result[0] & 0x40, 0x40);
        // Reserved bits must be cleared
        assert_eq!(result[0] & 0x18, 0x00);
    }

    #[test]
    fn build_padded_packet_zero_pad() {
        let payload = vec![0x01, 0x02];
        let result = build_padded_packet(&payload, 0, Protocol::Quic);
        assert_eq!(result.len(), 2);
        assert_eq!(&result[..], &[0x01, 0x02]);
    }

    #[test]
    fn build_padded_packet_sip() {
        let payload = vec![0xFF];
        let result = build_padded_packet(&payload, 4, Protocol::Sip);
        assert_eq!(result.len(), 5);
        // Last byte is payload
        assert_eq!(result[4], 0xFF);
        // SIP text fill, last 2 bytes of padding overridden with \r\n
        assert_eq!(result[0], b'V');
        assert_eq!(result[1], b'i');
        assert_eq!(result[2], b'\r');
        assert_eq!(result[3], b'\n');
    }

    #[test]
    fn build_padded_packet_dns() {
        let payload = vec![0x42, 0x43, 0x44];
        let result = build_padded_packet(&payload, 12, Protocol::Dns);
        assert_eq!(result.len(), 15);
        // Last 3 bytes are payload
        assert_eq!(&result[12..15], &[0x42, 0x43, 0x44]);
        // DNS header: TX ID from payload bytes 0-1
        assert_eq!(result[0], 0x42); // tx_hi
        assert_eq!(result[1], 0x43); // tx_lo
        // Flags: QR=1
        assert_eq!(result[2] & 0x80, 0x80);
    }

    // -- AWG-aware transform tests --

    fn test_awg_params() -> AwgParams {
        AwgParams {
            jc: 5,
            jmin: 50,
            jmax: 1000,
            s1: 10,
            s2: 8,
            s3: 6,
            s4: 20,
            h1: HRange { min: 100, max: 200 },
            h2: HRange { min: 300, max: 400 },
            h3: HRange { min: 500, max: 600 },
            h4: HRange { min: 700, max: 800 },
        }
    }

    #[test]
    fn awg_transform_handshake_init_quic() {
        let params = test_awg_params();
        // Build a packet: S1 prefix padding + H1-range header + body
        let padding_original = [0xFF; 10]; // S1 = 10 bytes of random prefix padding
        let header = 150u32.to_le_bytes();
        let body = [0xAA; 30]; // body portion
        let mut pkt = Vec::new();
        pkt.extend_from_slice(&padding_original);
        pkt.extend_from_slice(&header);
        pkt.extend_from_slice(&body);
        assert_eq!(pkt.len(), 44); // 10 + 4 + 30

        let result = apply_awg_transform(&mut pkt, &params, Protocol::Quic);
        assert!(result);

        // Prefix padding (first 10 bytes): first byte has QUIC fixed bit
        assert_eq!(pkt[0] & 0x40, 0x40);
        // Reserved bits must be cleared
        assert_eq!(pkt[0] & 0x18, 0x00);
        // Should have non-zero bytes (pseudo-random, not all-zero)
        assert!(pkt[1..10].iter().any(|&b| b != 0x00));
        // Header should be untouched
        assert_eq!(&pkt[10..14], &150u32.to_le_bytes());
        // Body should be untouched
        assert!(pkt[14..44].iter().all(|&b| b == 0xAA));
    }

    #[test]
    fn awg_transform_transport_data_sip() {
        let params = test_awg_params();
        // S4 = 20 bytes prefix + H4-range header + body
        let padding_original = [0xFF; 20]; // S4 = 20
        let header = 750u32.to_le_bytes();
        let body = [0xBB; 100];
        let mut pkt = Vec::new();
        pkt.extend_from_slice(&padding_original);
        pkt.extend_from_slice(&header);
        pkt.extend_from_slice(&body);

        let result = apply_awg_transform(&mut pkt, &params, Protocol::Sip);
        assert!(result);

        // Prefix padding should start with SIP text
        assert!(pkt[..20].starts_with(b"Via:"));
        // Padding ends with \r\n
        assert_eq!(pkt[18], b'\r');
        assert_eq!(pkt[19], b'\n');
        // Header + body should be untouched
        assert_eq!(&pkt[20..24], &750u32.to_le_bytes());
        assert!(pkt[24..124].iter().all(|&b| b == 0xBB));
    }

    #[test]
    fn awg_transform_handshake_response_dns() {
        let params = test_awg_params();
        // S2 = 8 bytes prefix + H2-range header + body
        let padding_original = [0xFF; 8]; // S2 = 8
        let header = 350u32.to_le_bytes();
        let body = [0xDD; 50];
        let mut pkt = Vec::new();
        pkt.extend_from_slice(&padding_original);
        pkt.extend_from_slice(&header);
        pkt.extend_from_slice(&body);

        let result = apply_awg_transform(&mut pkt, &params, Protocol::Dns);
        assert!(result);

        // Prefix padding (first 8 bytes): DNS header structure
        // Flags byte at offset 2 should have QR=1
        assert_eq!(pkt[2] & 0x80, 0x80);
        // Header should be untouched
        assert_eq!(&pkt[8..12], &350u32.to_le_bytes());
        // Body should be untouched
        assert!(pkt[12..62].iter().all(|&b| b == 0xDD));
    }

    #[test]
    fn awg_transform_unknown_packet() {
        let params = test_awg_params();
        let mut pkt = vec![0xFF; 50]; // No valid H-range header at any S offset
        let result = apply_awg_transform(&mut pkt, &params, Protocol::Quic);
        assert!(!result);
        // Packet should be unchanged
        assert!(pkt.iter().all(|&b| b == 0xFF));
    }

    #[test]
    fn awg_transform_padding_larger_than_packet() {
        let params = AwgParams {
            s1: 100, // padding larger than packet
            ..test_awg_params()
        };
        // Packet too short for S1(100) + 4 header bytes → can't classify
        let header = 150u32.to_le_bytes();
        let mut pkt = Vec::from(header); // only 4 bytes
        let result = apply_awg_transform(&mut pkt, &params, Protocol::Quic);
        assert!(!result); // can't classify (too short for S1 offset)
    }
}
