use bytes::{BytesMut, BufMut};

use crate::config::AwgParams;
use crate::responder::{Protocol, classify_awg_packet};

/// Apply protocol-conformant padding transformation to an outgoing packet.
///
/// AmneziaWG appends random padding bytes to WireGuard packets. When imitating
/// a specific protocol, we overwrite the padding region (bytes after the
/// WireGuard payload) with protocol-conformant filler so that DPI sees
/// plausible traffic.
///
/// The `payload_len` parameter indicates where the real WireGuard payload ends
/// within `data`. Everything from `payload_len..data.len()` is treated as
/// padding that gets overwritten.
///
/// If `payload_len >= data.len()`, no transformation is applied (no padding
/// region exists).
///
/// Protocol-specific padding strategies:
/// - **QUIC**: Pseudo-random bytes resembling encrypted QUIC payload (high
///   entropy), with a QUIC short-header form byte at the start.
/// - **DNS**: DNS response header structure (transaction ID, flags, section
///   counts) followed by zero-fill for EDNS OPT padding (RFC 7830).
/// - **SIP**: SIP header continuation text (`Via:`, `Content-Length:`)
///   ending with CRLF.
pub fn apply_padding(data: &mut [u8], payload_len: usize, proto: Protocol) {
    if payload_len >= data.len() {
        return;
    }

    match proto {
        Protocol::Quic => apply_quic_padding(data, payload_len),
        Protocol::Dns => apply_dns_padding(data, payload_len),
        Protocol::Sip => apply_sip_padding(data, payload_len),
    }
}

/// Apply AWG-aware padding transformation to an outgoing packet.
///
/// Classifies the packet using H1–H4 ranges to determine its type, then uses
/// the corresponding S-value to locate the padding region and overwrite it
/// with protocol-conformant filler.
///
/// Returns `true` if the packet was classified and transformed, `false` if the
/// packet type could not be identified (e.g. junk packet) and was left
/// unchanged.
pub fn apply_awg_transform(
    data: &mut [u8],
    params: &AwgParams,
    proto: Protocol,
) -> bool {
    let pkt_type = match classify_awg_packet(data, params) {
        Some(t) => t,
        None => return false,
    };

    let pad_size = pkt_type.padding_size(params);
    let total = data.len();

    if pad_size == 0 || pad_size >= total {
        return false;
    }

    let payload_end = total - pad_size;
    apply_padding(data, payload_end, proto);
    true
}

/// Build a complete packet with protocol-conformant padding appended.
///
/// Takes the original payload and appends `pad_len` bytes of
/// protocol-conformant padding.
pub fn build_padded_packet(payload: &[u8], pad_len: usize, proto: Protocol) -> BytesMut {
    let mut buf = BytesMut::with_capacity(payload.len() + pad_len);
    buf.put_slice(payload);

    if pad_len == 0 {
        return buf;
    }

    // Append padding bytes (initially zeros)
    buf.put_bytes(0, pad_len);

    let payload_end = payload.len();
    apply_padding(&mut buf[..], payload_end, proto);

    buf
}

// ---------------------------------------------------------------------------
// Protocol-specific padding implementations
// ---------------------------------------------------------------------------

/// QUIC-style padding: pseudo-random bytes resembling encrypted QUIC payload.
///
/// Encrypted QUIC data has high entropy (uniform byte distribution). The first
/// byte uses the QUIC short-header form (fixed bit set, `0x40`), and remaining
/// bytes are generated by a deterministic PRNG seeded from the packet payload.
/// This makes the padding indistinguishable from encrypted QUIC payload to
/// statistical DPI analysis.
fn apply_quic_padding(data: &mut [u8], payload_len: usize) {
    let (payload, padding) = data.split_at_mut(payload_len);
    if padding.is_empty() {
        return;
    }

    // Seed PRNG from payload bytes using FNV-1a hash
    let mut state: u32 = 0x811c_9dc5;
    for &b in payload.iter().take(64) {
        state ^= b as u32;
        state = state.wrapping_mul(0x0100_0193);
    }

    // Byte 0: QUIC short-header form byte (header form=0, fixed bit=1)
    padding[0] = 0x40 | ((state & 0x3F) as u8);
    state = lcg_step(state);

    // Remaining bytes: pseudo-random, simulating encrypted QUIC 1-RTT payload
    for byte in padding[1..].iter_mut() {
        *byte = (state >> 16) as u8;
        state = lcg_step(state);
    }
}

/// DNS-style padding: minimal DNS response header followed by zero padding.
///
/// Creates a plausible DNS response structure:
/// - Transaction ID derived from the packet payload
/// - Standard response flags (QR=1, RD=1, RA=1, RCODE=NOERROR)
/// - Remaining bytes are zero-filled (EDNS OPT padding option, RFC 7830)
fn apply_dns_padding(data: &mut [u8], payload_len: usize) {
    let (payload, padding) = data.split_at_mut(payload_len);
    if padding.is_empty() {
        return;
    }

    // Derive transaction ID from first two payload bytes
    let tx_hi = payload.first().copied().unwrap_or(0);
    let tx_lo = payload.get(1).copied().unwrap_or(0);

    // DNS response header (12 bytes)
    let header: [u8; 12] = [
        tx_hi, tx_lo,   // Transaction ID
        0x81, 0x80,     // Flags: QR=1, RD=1, RA=1, RCODE=NOERROR
        0x00, 0x01,     // QDCOUNT = 1
        0x00, 0x00,     // ANCOUNT = 0
        0x00, 0x00,     // NSCOUNT = 0
        0x00, 0x01,     // ARCOUNT = 1 (OPT pseudo-RR for EDNS)
    ];

    let copy_len = std::cmp::min(padding.len(), header.len());
    padding[..copy_len].copy_from_slice(&header[..copy_len]);

    // Rest: zero-fill (EDNS OPT padding option content is zeros per RFC 7830)
    for byte in padding[copy_len..].iter_mut() {
        *byte = 0x00;
    }
}

/// SIP-style padding: SIP header continuation text.
///
/// Fills the padding with recognizable SIP header text (`Via:`,
/// `Content-Length:`) which makes the packet look like legitimate SIP
/// signaling traffic. The padding always ends with CRLF when space allows.
fn apply_sip_padding(data: &mut [u8], payload_len: usize) {
    let padding = &mut data[payload_len..];
    if padding.is_empty() {
        return;
    }

    let len = padding.len();

    // SIP header continuation text
    static SIP_FILL: &[u8] = b"Via: SIP/2.0/UDP proxy\r\nContent-Length: 0\r\n";

    // Fill padding by cycling through the SIP text
    let fill_len = SIP_FILL.len();
    let mut pos = 0;
    while pos < len {
        let remaining = len - pos;
        let chunk = std::cmp::min(remaining, fill_len);
        padding[pos..pos + chunk].copy_from_slice(&SIP_FILL[..chunk]);
        pos += chunk;
    }

    // Ensure the padding ends with \r\n if at least 2 bytes
    if len >= 2 {
        padding[len - 2] = b'\r';
        padding[len - 1] = b'\n';
    }
}

/// Linear congruential generator step (glibc constants).
fn lcg_step(state: u32) -> u32 {
    state.wrapping_mul(1_103_515_245).wrapping_add(12345)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::HRange;

    // -- QUIC padding tests --

    #[test]
    fn quic_padding_has_header_and_entropy() {
        let mut data = vec![0xAA; 20];
        let payload_len = 10;
        apply_padding(&mut data, payload_len, Protocol::Quic);

        // First 10 bytes untouched
        assert!(data[..10].iter().all(|&b| b == 0xAA));
        // First padding byte has QUIC fixed bit set (0x40)
        assert_eq!(
            data[10] & 0x40,
            0x40,
            "QUIC padding first byte should have fixed bit set"
        );
        // Padding should contain non-zero bytes (high entropy, not all-zero)
        assert!(
            data[11..].iter().any(|&b| b != 0x00),
            "QUIC padding should have non-zero bytes"
        );
    }

    #[test]
    fn quic_padding_varies_with_payload() {
        // Two different payloads should produce different padding
        let mut data_a = vec![0xAA; 20];
        let mut data_b = vec![0xBB; 20];
        apply_padding(&mut data_a, 10, Protocol::Quic);
        apply_padding(&mut data_b, 10, Protocol::Quic);
        // Padding regions should differ (different seeds from different payloads)
        assert_ne!(&data_a[10..], &data_b[10..]);
    }

    // -- DNS padding tests --

    #[test]
    fn dns_padding_has_response_header() {
        let mut data = vec![0xBB; 24];
        let payload_len = 4;
        apply_padding(&mut data, payload_len, Protocol::Dns);

        // First 4 bytes untouched
        assert!(data[..4].iter().all(|&b| b == 0xBB));
        // DNS response header: TX ID derived from payload bytes
        assert_eq!(data[4], 0xBB); // tx_hi from payload[0]
        assert_eq!(data[5], 0xBB); // tx_lo from payload[1]
        // Flags: QR=1 (high bit of flags byte)
        assert_eq!(data[6] & 0x80, 0x80, "DNS QR bit should be set");
        assert_eq!(data[6], 0x81); // RD=1
        assert_eq!(data[7], 0x80); // RA=1
        // QDCOUNT = 1
        assert_eq!(data[8], 0x00);
        assert_eq!(data[9], 0x01);
        // After header (12 bytes), rest should be zeros (EDNS padding)
        assert!(data[16..].iter().all(|&b| b == 0x00));
    }

    #[test]
    fn dns_padding_short_fills_partial_header() {
        // Only 5 bytes of padding — should fill what fits from DNS header
        let mut data = vec![0xCC; 10];
        let payload_len = 5;
        apply_padding(&mut data, payload_len, Protocol::Dns);

        assert!(data[..5].iter().all(|&b| b == 0xCC));
        assert_eq!(data[5], 0xCC); // tx_hi from payload[0]
        assert_eq!(data[6], 0xCC); // tx_lo from payload[1]
        assert_eq!(data[7], 0x81); // flags high
        assert_eq!(data[8], 0x80); // flags low
        assert_eq!(data[9], 0x00); // QDCOUNT high
    }

    // -- SIP padding tests --

    #[test]
    fn sip_padding_has_sip_headers() {
        let mut data = vec![0xCC; 60];
        let payload_len = 10;
        apply_padding(&mut data, payload_len, Protocol::Sip);

        // First 10 bytes untouched
        assert!(data[..10].iter().all(|&b| b == 0xCC));
        // Padding starts with "Via: SIP/2.0/..."
        let padding = &data[10..];
        assert!(padding.starts_with(b"Via: SIP"));
        // Ends with \r\n
        let len = data.len();
        assert_eq!(data[len - 2], b'\r');
        assert_eq!(data[len - 1], b'\n');
    }

    #[test]
    fn sip_padding_single_byte() {
        let mut data = [0xAA, 0x00];
        apply_padding(&mut data, 1, Protocol::Sip);
        // Single byte gets first char of SIP fill text
        assert_eq!(data[1], b'V');
    }

    #[test]
    fn sip_padding_two_bytes() {
        let mut data = [0xAA, 0x00, 0x00];
        apply_padding(&mut data, 1, Protocol::Sip);
        // Two bytes: ends with \r\n
        assert_eq!(data[1], b'\r');
        assert_eq!(data[2], b'\n');
    }

    // -- General padding tests --

    #[test]
    fn no_padding_when_payload_equals_len() {
        let mut data = vec![0xDD; 10];
        apply_padding(&mut data, 10, Protocol::Quic);
        assert!(data.iter().all(|&b| b == 0xDD));
    }

    #[test]
    fn no_padding_when_payload_exceeds_len() {
        let mut data = vec![0xEE; 10];
        apply_padding(&mut data, 15, Protocol::Dns);
        assert!(data.iter().all(|&b| b == 0xEE));
    }

    // -- Build padded packet tests --

    #[test]
    fn build_padded_packet_quic() {
        let payload = vec![0x01, 0x02, 0x03];
        let result = build_padded_packet(&payload, 5, Protocol::Quic);
        assert_eq!(result.len(), 8);
        assert_eq!(&result[..3], &[0x01, 0x02, 0x03]);
        // First padding byte has QUIC fixed bit
        assert_eq!(result[3] & 0x40, 0x40);
    }

    #[test]
    fn build_padded_packet_zero_pad() {
        let payload = vec![0x01, 0x02];
        let result = build_padded_packet(&payload, 0, Protocol::Quic);
        assert_eq!(result.len(), 2);
        assert_eq!(&result[..], &[0x01, 0x02]);
    }

    #[test]
    fn build_padded_packet_sip() {
        let payload = vec![0xFF];
        let result = build_padded_packet(&payload, 4, Protocol::Sip);
        assert_eq!(result.len(), 5);
        assert_eq!(result[0], 0xFF);
        // SIP text fill, last 2 bytes overridden with \r\n
        assert_eq!(result[1], b'V');
        assert_eq!(result[2], b'i');
        assert_eq!(result[3], b'\r');
        assert_eq!(result[4], b'\n');
    }

    #[test]
    fn build_padded_packet_dns() {
        let payload = vec![0x42, 0x43, 0x44];
        let result = build_padded_packet(&payload, 12, Protocol::Dns);
        assert_eq!(result.len(), 15);
        assert_eq!(&result[..3], &[0x42, 0x43, 0x44]);
        // DNS header: TX ID from payload bytes 0-1
        assert_eq!(result[3], 0x42); // tx_hi
        assert_eq!(result[4], 0x43); // tx_lo
        // Flags: QR=1
        assert_eq!(result[5] & 0x80, 0x80);
    }

    // -- AWG-aware transform tests --

    fn test_awg_params() -> AwgParams {
        AwgParams {
            jc: 5,
            jmin: 50,
            jmax: 1000,
            s1: 10,
            s2: 8,
            s3: 6,
            s4: 20,
            h1: HRange { min: 100, max: 200 },
            h2: HRange { min: 300, max: 400 },
            h3: HRange { min: 500, max: 600 },
            h4: HRange { min: 700, max: 800 },
        }
    }

    #[test]
    fn awg_transform_handshake_init_quic() {
        let params = test_awg_params();
        // Build a packet with header in H1 range + body + S1 padding
        let header = 150u32.to_le_bytes();
        let body = [0xAA; 30]; // body portion
        let padding_original = [0xFF; 10]; // S1 = 10 bytes of random padding
        let mut pkt = Vec::new();
        pkt.extend_from_slice(&header);
        pkt.extend_from_slice(&body);
        pkt.extend_from_slice(&padding_original);
        assert_eq!(pkt.len(), 44); // 4 + 30 + 10

        let result = apply_awg_transform(&mut pkt, &params, Protocol::Quic);
        assert!(result);

        // Body should be untouched
        assert!(pkt[4..34].iter().all(|&b| b == 0xAA));
        // Padding (last 10 bytes): first byte has QUIC fixed bit
        assert_eq!(pkt[34] & 0x40, 0x40);
        // Should have non-zero bytes (pseudo-random, not all-zero)
        assert!(pkt[35..].iter().any(|&b| b != 0x00));
    }

    #[test]
    fn awg_transform_transport_data_sip() {
        let params = test_awg_params();
        let header = 750u32.to_le_bytes();
        let body = [0xBB; 100];
        let padding_original = [0xFF; 20]; // S4 = 20
        let mut pkt = Vec::new();
        pkt.extend_from_slice(&header);
        pkt.extend_from_slice(&body);
        pkt.extend_from_slice(&padding_original);

        let result = apply_awg_transform(&mut pkt, &params, Protocol::Sip);
        assert!(result);

        // Padding should start with SIP text
        let pad_start = pkt.len() - 20;
        assert!(pkt[pad_start..].starts_with(b"Via:"));
        // Ends with \r\n
        assert_eq!(pkt[pkt.len() - 2], b'\r');
        assert_eq!(pkt[pkt.len() - 1], b'\n');
    }

    #[test]
    fn awg_transform_handshake_response_dns() {
        let params = test_awg_params();
        let header = 350u32.to_le_bytes();
        let body = [0xDD; 50];
        let padding_original = [0xFF; 8]; // S2 = 8
        let mut pkt = Vec::new();
        pkt.extend_from_slice(&header);
        pkt.extend_from_slice(&body);
        pkt.extend_from_slice(&padding_original);

        let result = apply_awg_transform(&mut pkt, &params, Protocol::Dns);
        assert!(result);

        // Body should be untouched
        assert!(pkt[4..54].iter().all(|&b| b == 0xDD));
        // Padding (last 8 bytes): DNS header structure
        let pad_start = pkt.len() - 8;
        // Flags byte at offset +2 should have QR=1
        assert_eq!(pkt[pad_start + 2] & 0x80, 0x80);
    }

    #[test]
    fn awg_transform_unknown_packet() {
        let params = test_awg_params();
        let mut pkt = vec![0xFF; 50]; // Header not in any H range
        let result = apply_awg_transform(&mut pkt, &params, Protocol::Quic);
        assert!(!result);
        // Packet should be unchanged
        assert!(pkt.iter().all(|&b| b == 0xFF));
    }

    #[test]
    fn awg_transform_padding_larger_than_packet() {
        let params = AwgParams {
            s1: 100, // padding larger than packet
            ..test_awg_params()
        };
        let header = 150u32.to_le_bytes();
        let mut pkt = Vec::from(header); // only 4 bytes
        let result = apply_awg_transform(&mut pkt, &params, Protocol::Quic);
        assert!(!result); // can't apply padding
    }
}
